import { computed, ref } from 'vue'
import { APP_VERSION } from './version'

export type Locale = 'zh' | 'en'

const saved = localStorage.getItem('locale') as Locale | null
const locale = ref<Locale>(saved === 'en' ? 'en' : 'zh')

const retryIntervalLabels = {
  zh: { probeRetryInterval: '异常源重试间隔（分钟）', probeRetryIntervalHint: '错误、未知、离线或降级的镜像源按此间隔重试。' },
  en: { probeRetryInterval: 'Unhealthy retry interval (minutes)', probeRetryIntervalHint: 'Error, unknown, offline, or degraded sources are retried at this interval.' },
} as const

const zh = {
  ...retryIntervalLabels.zh,
  adminCredentials: '\u51ed\u8bc1\u914d\u7f6e', credentialName: '\u540d\u79f0', credentialType: '\u8ba4\u8bc1\u7c7b\u578b', credentialSelector: '\u5339\u914d\u8303\u56f4', credentialSecret: '\u5bc6\u94a5', credentialSource: '\u955c\u50cf\u6e90', credentialHost: '\u6ce8\u518c\u8868\u57df\u540d', credentialCategory: '\u955c\u50cf\u6e90\u7c7b\u522b', credentialSelectorHint: '\u51ed\u8bc1\u5339\u914d\u4f18\u5148\u7ea7\uff1a\u6e90 > \u57df\u540d > \u7c7b\u522b\uff1b\u5bc6\u94a5\u52a0\u5bc6\u5b58\u50a8\uff0c\u754c\u9762\u4e0d\u8fd4\u56de\u660e\u6587\u3002', credentialBasic: '\u57fa\u672c\u8ba4\u8bc1', credentialBearer: 'Bearer Token', credentialToken: 'Token', credentialSecretPlaceholder: '\u7559\u7a7a\u4ee5\u4fdd\u7559\u539f\u5bc6\u94a5', credentialNoSecret: '\u672a\u8bbe\u7f6e', credentialSaveError: '\u51ed\u8bc1\u4fdd\u5b58\u5931\u8d25', credentialDeleteError: '\u51ed\u8bc1\u5220\u9664\u5931\u8d25',
  categoryKey: '\u7c7b\u522b\u6807\u8bc6',
  podmanRegistryHint: '生成按当前镜像源类别匹配的 Podman registries.conf', pullTagCommands: 'docker pull / docker tag 命令',
  sourceCategories: '镜像源类别',
  sameCategoryHint: '请选择同一镜像源类别的站点后生成配置', dockerHubConfigHint: 'Docker Hub 支持生成 daemon.json 等运行时配置', registryConfigHint: '非 Docker Hub 镜像源请使用镜像前缀方式拉取', registryCommandHint: '将 user/image:tag 替换为实际镜像名称和标签',
  testImage: '测试镜像', systemDefaultTestImage: '系统默认测试镜像', defaultImage: '默认', setDefaultImage: '设为默认', applicableCategories: '适用分类', applicableProbeModes: '适用探测模式', noLimit: '不限制', selectedScopeHint: '已选择范围', noApplicableTestImages: '当前分类和探测模式没有可用的启用测试镜像', authStrategy: '认证策略', authAnonymous: '匿名', authOptional: '可选认证', authRequired: '必须认证', authConfigured: '已配置', authNotConfigured: '未配置', authStatusUnknown: '状态未知', authSecretHint: '仅保存认证策略；密钥只显示配置状态，不在此处显示。',
  sortOrder: '排序号', associatedSources: '关联源数', associatedUsers: '关联用户数', categoryInUse: '该分类已关联镜像源，不能删除',
  home: '首页', tutorial: '教程', about: '关于', admin: '管理后台', configure: '配置生成器', brand: '容器镜像仓库实时监控',
  footer: '状态由后端真实探测生成 · 第三方镜像源可能随时变化', createdAt: '添加时间', runtimeDuration: '运行时间', all: '全部镜像源', categories: '镜像源分类', sources: '镜像源状态',
  total: '监控站点', online: '运行', degraded: '响应缓慢', offline: '离线', maintenance: '维护', refresh: '刷新数据',
  search: '搜索名称、域名或提供商', filterTags: '按标签筛选', loading: '正在加载实时监控数据…', noResults: '没有匹配的镜像源',
  response: '响应时间', unknown: '未知', status: '状态', sort: '排序', sortStatus: '状态', sortLatency: '响应时间', sortName: '名称',
  asc: '升序', desc: '降序', apiError: '暂时无法连接监控 API', liveMonitoring: '实时监控平台', heroTitle: '镜像源状态，', heroAccent: '一目了然',
  heroDescription: '通过真实的 DNS、TCP、TLS 与 Registry API 探测，持续了解容器镜像源的可用性和响应速度。', viewStatus: '查看实时状态',
  lastUpdated: '最近更新', autoRefresh: '每 60 秒自动刷新', availability: '可用率', liveData: '实时数据', monitoredSites: '个监控站点', operational: '运行正常',
  needsAttention: '需要关注', unavailable: '暂不可用', of: '/', registry: '镜像源', needConfig: '准备配置 Docker？', needConfigHint: '选择在线镜像源，快速生成运行时配置。', openGenerator: '打开配置生成器',
  adminTitle: '镜像源管理后台', loginHint: '使用管理员 Bearer Token 登录', token: '管理员 Token', tokenHint: '粘贴 Token', add: '新增', edit: '编辑', remove: '删除',
  account: '账户', sessionToken: '当前会话 Token', sessionTokenHint: '登录会话认证凭证，由系统自动管理', sourceActions: '镜像源操作', selected: '已选择', selectAllPage: '全选当前页', clearAllPage: '取消全选当前页', probeInterval: '镜像检测间隔（分钟）', probeIntervalHint: '后台 Worker 按此间隔开始新一轮检测；不会影响首页刷新频率。', totpTitle: 'TOTP', totpDescription: '为管理员账户启用身份验证器验证码。', generateSecret: '生成密钥', secret: '密钥', otpUri: '配置 URI', verificationCode: '验证码', totpHint: '将密钥添加到 Google Authenticator、Microsoft Authenticator 或其他 TOTP 应用后，输入当前验证码完成绑定。', enableTotp: '启用 TOTP', disableTotp: '关闭 TOTP', disabled: '已禁用', monitoringStatus: '检测状态', enabledStatus: '启用状态', close: '关闭', saveSuccess: '保存成功', deleteSuccess: '删除成功', deleteQueued: '删除任务已提交，记录已隐藏', probeQueued: '探测任务已加入队列', importSuccess: '导入成功',
  saveError: '保存失败', deleteError: '删除失败', probeError: '无法创建探测任务', importError: '导入失败', categorySaveError: '分类保存失败', categoryDeleteError: '分类删除失败', testImageSaveError: '测试镜像保存失败', testImageDeleteError: '测试镜像删除失败', settingsSaveError: '设置保存失败', taskUpdateError: '任务更新失败', notificationTestError: '通知测试发送失败', registryUpdateError: '镜像源更新失败', exportError: '导出失败',
  adminMenu: '\u7ba1\u7406\u83dc\u5355', backToSite: '\u8fd4\u56de\u524d\u53f0', adminLoginTitle: '\u7ba1\u7406\u540e\u53f0\u767b\u5f55', adminLoginDescription: '\u8bf7\u8f93\u5165\u7ba1\u7406\u5458\u8d26\u53f7\u548c\u5bc6\u7801\u7ee7\u7eed', username: '\u7528\u6237\u540d', password: '\u5bc6\u7801', totp: 'TOTP \u9a8c\u8bc1\u7801', signIn: '\u767b\u5f55', signOut: '\u9000\u51fa', currentPassword: '\u5f53\u524d\u5bc6\u7801', newPassword: '\u65b0\u5bc6\u7801', changePassword: '\u4fee\u6539\u5bc6\u7801',
  adminSources: '\u955c\u50cf\u6e90', adminCategories: '\u5206\u7c7b', adminTasks: '\u63a2\u6d4b\u4efb\u52a1', adminNodes: '\u63a2\u6d4b\u8282\u70b9', adminUsers: '\u7528\u6237', adminRoles: '\u89d2\u8272', adminNotifications: '\u901a\u77e5', adminNotificationRules: '\u901a\u77e5\u89c4\u5219', adminTestImages: '\u6d4b\u8bd5\u955c\u50cf', adminSettings: '\u8bbe\u7f6e', enable: '\u542f\u7528', disable: '\u7981\u7528', enableSelected: '\u542f\u7528\u9009\u4e2d', disableSelected: '\u7981\u7528\u9009\u4e2d', exportJson: '\u5bfc\u51fa JSON', exportCsv: '\u5bfc\u51fa CSV', importData: '\u5bfc\u5165', deleteUser: '\u5220\u9664\u7528\u6237', resetTotp: '\u91cd\u7f6e TOTP', deleteRole: '\u5220\u9664\u89d2\u8272', roleInUse: '\u89d2\u8272\u5df2\u88ab\u7528\u6237\u5173\u8054', builtinRole: '\u7cfb\u7edf\u89d2\u8272\u4e0d\u5141\u8bb8\u5220\u9664', mustDisableUser: '\u8bf7\u5148\u7981\u7528\u7528\u6237\u518d\u5220\u9664', totpAccount: '\u8d26\u6237 TOTP', totpAccountHint: '\u4e3a\u5f53\u524d\u8d26\u6237\u914d\u7f6e\u9a8c\u8bc1\u5668\u5b89\u5168\u7801', totpConfigured: '\u5df2\u914d\u7f6e', totpNotConfigured: '\u672a\u914d\u7f6e',
  country: '\u56fd\u5bb6\u6216\u5730\u533a', operator: '\u8fd0\u8425\u65b9', description: '\u63cf\u8ff0', tags: '\u6807\u7b7e', testRepository: '\u6d4b\u8bd5\u4ed3\u5e93', testTag: '\u6d4b\u8bd5\u6807\u7b7e', timeout: '\u8d85\u65f6\u79d2\u6570', downloadBytes: '\u4e0b\u8f7d\u5b57\u8282', official: '\u5b98\u65b9', recommended: '\u63a8\u8350', probeMode: '\u63a2\u6d4b\u6a21\u5f0f', registryProbe: '\u6ce8\u518c\u8868\u63a2\u6d4b', manifestProbe: '\u6e05\u5355\u63a2\u6d4b', httpProbe: 'HTTP(S) \u63a2\u6d4b', dockerPullProbe: 'Docker Pull \u63a2\u6d4b', customProbeConfig: '\u81ea\u5b9a\u4e49\u6d4b\u914d\u7f6e', defaultProbeConfigIs: '\u9ed8\u8ba4\u914d\u7f6e\u4e3a\uff1a', defaultProbeMode: '\u9ed8\u8ba4\u63a2\u6d4b\u6a21\u5f0f', defaultTimeout: '\u9ed8\u8ba4\u8d85\u65f6\uff08\u79d2\uff09', actions: '\u64cd\u4f5c', probe: '\u63a2\u6d4b',
  categoriesTitle: '\u5206\u7c7b', probeTasks: '\u63a2\u6d4b\u4efb\u52a1', probeNodes: '\u63a2\u6d4b\u8282\u70b9', usersTitle: '\u7528\u6237', rolesTitle: '\u89d2\u8272', notificationsTitle: '\u901a\u77e5', notificationRulesTitle: '\u901a\u77e5\u89c4\u5219', testImagesTitle: '\u6d4b\u8bd5\u955c\u50cf', settingsTitle: '\u8bbe\u7f6e', id: 'ID', slug: 'Slug', enabled: '\u542f\u7528', lastSeen: '\u6700\u540e\u5728\u7ebf', permissions: '\u6743\u9650', reference: '\u955c\u50cf\u5f15\u7528', maxBytes: '\u6700\u5927\u5927\u5c0f\uff08M\uff09', event: '\u4e8b\u4ef6', channel: '\u6e20\u9053', cooldown: '\u51b7\u5374\u65f6\u95f4', aggregation: '\u805a\u5408\u65f6\u95f4', type: '\u7c7b\u578b', sendTest: '\u53d1\u9001\u6d4b\u8bd5', delete: '\u5220\u9664', retry: '\u91cd\u8bd5', version: '\u7248\u672c', saveSettings: '\u4fdd\u5b58\u8bbe\u7f6e', saved: '\u5df2\u4fdd\u5b58', imported: '\u5df2\u5bfc\u5165', savedPasswordHint: '\u5bc6\u7801\u5df2\u4fee\u6539\uff0c\u8bf7\u91cd\u65b0\u767b\u5f55',
  save: '保存', cancel: '取消', confirmDelete: '确定要删除这条记录吗？', name: '名称', url: '地址', category: '分类', provider: '提供商', region: '地区', prevent: '请先备份配置',
  copied: '已复制', copy: '复制', docker: 'Docker', podman: 'Podman', containerd: 'Containerd', nerdctl: 'Nerdctl', guide: '教程', configuration: '配置', input: '输入', output: '输出', runtime: '运行时', mirrorUrls: '镜像源地址', runtimeAndMirrors: '运行时与镜像地址', generatedConfig: '生成配置', configDialogTitle: '从已选镜像源生成配置', selectedSourcesPrefix: '已选择 ', selectedSourcesSuffix: ' 个镜像源', configDialogHint: '配置将只使用当前选中的地址', clearSelection: '清空选择', done: '完成', contents: '目录', guideTitle: '配置容器镜像源', guideDescription: '从备份、配置到验证，按顺序完成运行时切换。', guideDocker: 'Docker Linux', guideOther: 'Podman 与 Containerd', guideVerify: '验证配置', guideNotice: '使用前请备份原配置，并确认镜像源符合你的供应链安全要求。第三方镜像源可能随时失效。', guideDockerBody: '创建或编辑', guideDockerBodyAfter: '写入 JSON 格式的 registry-mirrors，然后执行：', guideOtherBody: '分别编辑 /etc/containers/registries.conf 或 Containerd 的 hosts 配置，并注意不同版本的格式差异。', aboutTitle: '关于镜像脉动', aboutDescription: '面向自托管环境的容器镜像仓库可用性监控平台。', projectInfo: '软件信息', softwareName: '镜像脉动', softwareVersion: '', copyrightLabel: '版权所有', copyrightHolder: 'BeebOu', websiteLabel: '项目地址', projectWebsite: 'https://soft.54bb.com', rightsLabel: '权利声明', rightsReserved: '保留所有权利', aboutIntroTitle: '真实探测，而不是静态清单', aboutIntroBody: '平台从后端执行 DNS、TCP、TLS 和 OCI Registry 探测，并保存结果供状态页面使用。', security: '安全', securityTitle: '隐私与安全', securityBody: '默认阻止本地、私有、链路本地和云元数据地址；日志不记录密码、Cookie、Authorization 或完整 Token。', license: '协议', licenseTitle: 'AGPL-3.0 开源协议', licenseBody: '本软件使用 GNU Affero General Public License v3.0（AGPL-3.0）授权。第三方镜像源状态不构成可用性或安全性保证。', value: '内容',
  history: '历史记录', checked: '检查时间', monitorTime: '监测时间', latency: '延迟', error: '错误', emptyHistory: '暂无历史记录', message: '消息', time: '时间', count: '数量',
  item: '项目', x: '时间', y: '响应时间', regionLabel: '地区', trend: '趋势', detail: '详情', latest: '最新状态', samples: '样本数', max: '最大值',
  occurrences: '次', faultTimeline: '故障时间线', noFaults: '暂无故障记录', noTrend: '样本不足，暂时无法生成趋势', faultStart: '开始', faultEnd: '结束',
  recovered: '已恢复', startedAt: '开始时间', endedAt: '结束时间',
}

const en = {
  ...retryIntervalLabels.en,
  adminCredentials: 'Credentials', credentialName: 'Name', credentialType: 'Auth type', credentialSelector: 'Match scope', credentialSecret: 'Secret', credentialSource: 'Registry source', credentialHost: 'Registry host', credentialCategory: 'Registry category', credentialSelectorHint: 'Credential matching precedence: source > host > category. Secrets are encrypted at rest and never returned in plaintext.', credentialBasic: 'Basic auth', credentialBearer: 'Bearer token', credentialToken: 'Token', credentialSecretPlaceholder: 'Leave blank to keep the current secret', credentialNoSecret: 'Not set', credentialSaveError: 'Unable to save credential', credentialDeleteError: 'Unable to delete credential',
  categoryKey: 'Category key',
  podmanRegistryHint: 'Generate Podman registries.conf for the selected registry category', pullTagCommands: 'docker pull / docker tag commands',
  sourceCategories: 'Registry categories',
  sameCategoryHint: 'Select sources from the same registry category to generate a configuration', dockerHubConfigHint: 'Docker Hub supports daemon.json and other runtime configurations', registryConfigHint: 'For non-Docker Hub registries, use the mirror as an image prefix', registryCommandHint: 'Replace user/image:tag with the actual image and tag',
  testImage: 'Test image', systemDefaultTestImage: 'System default test image', defaultImage: 'Default', setDefaultImage: 'Set default', applicableCategories: 'Applicable categories', applicableProbeModes: 'Applicable probe modes', noLimit: 'No restriction', selectedScopeHint: 'Restricted to selected values', noApplicableTestImages: 'No enabled test image matches this category and probe mode', authStrategy: 'Authentication strategy', authAnonymous: 'Anonymous', authOptional: 'Optional authentication', authRequired: 'Authentication required', authConfigured: 'Configured', authNotConfigured: 'Not configured', authStatusUnknown: 'Status unavailable', authSecretHint: 'Only the authentication strategy is stored here; secrets are represented by configuration status and never shown.',
  sortOrder: 'Sort order', associatedSources: 'Associated sources', associatedUsers: 'Users', categoryInUse: 'This category has associated sources and cannot be deleted',
  home: 'Home', tutorial: 'Guide', about: 'About', admin: 'Admin', configure: 'Config generator', brand: 'Container registry monitor',
  footer: 'Status comes from live probes · Third-party registries may change', createdAt: 'Added at', runtimeDuration: 'Runtime', all: 'All registries', categories: 'Categories', sources: 'Registry status',
  total: 'Monitored sites', online: 'Online', degraded: 'Degraded', offline: 'Offline', maintenance: 'Maintenance', refresh: 'Refresh',
  search: 'Search name, domain or provider', filterTags: 'Filter by tag', loading: 'Loading live monitoring data…', noResults: 'No matching registries',
  response: 'Response time', unknown: 'Unknown', status: 'Status', sort: 'Sort', sortStatus: 'Status', sortLatency: 'Latency', sortName: 'Name',
  asc: 'Ascending', desc: 'Descending', apiError: 'Unable to connect to the monitoring API', liveMonitoring: 'Live monitoring platform', heroTitle: 'Registry status, ', heroAccent: 'at a glance',
  heroDescription: 'Real DNS, TCP, TLS and Registry API probes keep you informed about availability and response speed.', viewStatus: 'View live status',
  lastUpdated: 'Last updated', autoRefresh: 'auto refresh 60s', availability: 'availability', liveData: 'Live data', monitoredSites: 'monitored sites', operational: 'operational',
  needsAttention: 'needs attention', unavailable: 'currently unavailable', of: '/', registry: 'Registry', needConfig: 'Configuring Docker?', needConfigHint: 'Choose online registries and generate a runtime configuration.', openGenerator: 'Open generator',
  adminTitle: 'Registry Source Admin', loginHint: 'Sign in with an administrator Bearer token', token: 'Admin token', tokenHint: 'Enter a token and press Enter to reload', add: 'Add', edit: 'Edit', remove: 'Delete',
  account: 'Account', sessionToken: 'Current session token', sessionTokenHint: 'Login session credential managed automatically by the system', sourceActions: 'Actions', selected: 'selected', selectAllPage: 'Select current page', clearAllPage: 'Clear current page', probeInterval: 'Probe interval (minutes)', probeIntervalHint: 'The worker starts a new probe round at this interval; it does not change homepage refresh frequency.', totpTitle: 'TOTP', totpDescription: 'Enable authenticator codes for the administrator account.', generateSecret: 'Generate secret', secret: 'Secret', otpUri: 'Setup URI', verificationCode: 'Verification code', totpHint: 'Add the secret to Google Authenticator, Microsoft Authenticator, or another TOTP app, then enter the current code to finish binding.', enableTotp: 'Enable TOTP', disableTotp: 'Disable TOTP', disabled: 'Disabled', monitoringStatus: 'Probe status', enabledStatus: 'Enabled', close: 'Close', saveSuccess: 'Saved successfully', deleteSuccess: 'Deleted successfully', deleteQueued: 'Delete queued; the record is now hidden', probeQueued: 'Probe task queued', importSuccess: 'Imported successfully',
  saveError: 'Unable to save', deleteError: 'Unable to delete', probeError: 'Unable to queue probe', importError: 'Unable to import', categorySaveError: 'Unable to save category', categoryDeleteError: 'Unable to delete category', testImageSaveError: 'Unable to save test image', testImageDeleteError: 'Unable to delete test image', settingsSaveError: 'Unable to save settings', taskUpdateError: 'Unable to update task', notificationTestError: 'Unable to send notification test', registryUpdateError: 'Unable to update registries', exportError: 'Unable to export',
  adminMenu: 'Admin menu', backToSite: 'Back to site', adminLoginTitle: 'Admin sign in', adminLoginDescription: 'Enter administrator credentials to continue', username: 'Username', password: 'Password', totp: 'TOTP code', signIn: 'Sign in', signOut: 'Sign out', currentPassword: 'Current password', newPassword: 'New password', changePassword: 'Change password',
  adminSources: 'Sources', adminCategories: 'Categories', adminTasks: 'Tasks', adminNodes: 'Probe nodes', adminUsers: 'Users', adminRoles: 'Roles', adminNotifications: 'Notifications', adminNotificationRules: 'Notification rules', adminTestImages: 'Test images', adminSettings: 'Settings', enable: 'Enable', disable: 'Disable', enableSelected: 'Enable', disableSelected: 'Disable', exportJson: 'Export JSON', exportCsv: 'Export CSV', importData: 'Import', deleteUser: 'Delete user', resetTotp: 'Reset TOTP', deleteRole: 'Delete role', roleInUse: 'Role is assigned to users', builtinRole: 'Built-in roles cannot be deleted', mustDisableUser: 'Disable the user before deleting it', totpAccount: 'Account TOTP', totpAccountHint: 'Configure an authenticator for the current account', totpConfigured: 'Configured', totpNotConfigured: 'Not configured',
  country: 'Country', operator: 'Operator', description: 'Description', tags: 'Tags', testRepository: 'Test repository', testTag: 'Test tag', timeout: 'Timeout (seconds)', downloadBytes: 'Download bytes', official: 'Official', recommended: 'Recommended', probeMode: 'Probe mode', registryProbe: 'Registry API + blob probe', manifestProbe: 'OCI manifest probe', httpProbe: 'HTTP(S) probe', dockerPullProbe: 'Docker Pull probe', customProbeConfig: 'Custom probe', defaultProbeConfigIs: 'Default: ', defaultProbeMode: 'Default probe mode', defaultTimeout: 'Default timeout (seconds)', actions: 'Actions', probe: 'Probe',
  categoriesTitle: 'Categories', probeTasks: 'Probe tasks', probeNodes: 'Probe nodes', usersTitle: 'Users', rolesTitle: 'Roles', notificationsTitle: 'Notifications', notificationRulesTitle: 'Notification rules', testImagesTitle: 'Test images', settingsTitle: 'Settings', id: 'ID', slug: 'Slug', enabled: 'Enabled', lastSeen: 'Last seen', permissions: 'Permissions', reference: 'Image reference', maxBytes: 'Max size (M)', event: 'Event', channel: 'Channel', cooldown: 'Cooldown', aggregation: 'Aggregation', type: 'Type', sendTest: 'Send test', delete: 'Delete', retry: 'Retry', version: 'Version', saveSettings: 'Save settings', saved: 'Saved', imported: 'Imported', savedPasswordHint: 'Password changed; please sign in again',
  save: 'Save', cancel: 'Cancel', confirmDelete: 'Delete this record?', name: 'Name', url: 'URL', category: 'Category', provider: 'Provider', region: 'Region', prevent: 'Back up configuration first',
  copied: 'Copied', copy: 'Copy', docker: 'Docker', podman: 'Podman', containerd: 'Containerd', nerdctl: 'Nerdctl', guide: 'Guide', configuration: 'Configuration', input: 'Input', output: 'Output', runtime: 'Runtime', mirrorUrls: 'Mirror URLs', runtimeAndMirrors: 'Runtime and mirror URLs', generatedConfig: 'Generated configuration', configDialogTitle: 'Generate configuration from selected registries', selectedSourcesPrefix: '', selectedSourcesSuffix: ' sources selected', configDialogHint: 'Only the currently selected addresses will be used', clearSelection: 'Clear selection', done: 'Done', contents: 'Contents', guideTitle: 'Configure container registries', guideDescription: 'Back up, configure, and verify your runtime in order.', guideDocker: 'Docker Linux', guideOther: 'Podman and Containerd', guideVerify: 'Verify configuration', guideNotice: 'Back up the original configuration first and review the supply-chain risks of each registry. Third-party mirrors may become unavailable at any time.', guideDockerBody: 'Create or edit', guideDockerBodyAfter: 'write registry-mirrors in JSON format, then run:', guideOtherBody: 'Edit /etc/containers/registries.conf or the Containerd hosts configuration, and account for format differences between versions.', aboutTitle: 'About 镜像脉动', aboutDescription: 'A self-hosted platform for monitoring container registry availability.', projectInfo: 'Software information', softwareName: '镜像脉动', softwareVersion: '', copyrightLabel: 'Copyright', copyrightHolder: 'BeebOu', websiteLabel: 'Website', projectWebsite: 'https://soft.54bb.com', rightsLabel: 'Rights', rightsReserved: 'All rights reserved', aboutIntroTitle: 'Live probes, not a static list', aboutIntroBody: 'The backend runs DNS, TCP, TLS, and OCI Registry probes and stores results for the status pages.', security: 'Security', securityTitle: 'Privacy and security', securityBody: 'Local, private, link-local, and cloud metadata addresses are blocked by default; logs do not record passwords, cookies, Authorization headers, or complete tokens.', license: 'License', licenseTitle: 'AGPL-3.0 Open Source License', licenseBody: 'This software is licensed under the GNU Affero General Public License v3.0 (AGPL-3.0). Third-party registry status does not guarantee availability or security.', value: 'Value',
  history: 'History', checked: 'Checked at', monitorTime: 'Monitor time', latency: 'Latency', error: 'Error', emptyHistory: 'No history yet', message: 'Message', time: 'Time', count: 'Count',
  item: 'Item', x: 'Time', y: 'Response time', regionLabel: 'Region', trend: 'Trend', detail: 'Details', latest: 'Latest status', samples: 'Samples', max: 'Maximum',
  occurrences: 'occurrences', faultTimeline: 'Incident timeline', noFaults: 'No incidents recorded', noTrend: 'Not enough samples for a trend', faultStart: 'Started', faultEnd: 'Ended',
  recovered: 'Recovered', startedAt: 'Started', endedAt: 'Ended',
}

zh.softwareVersion = `v${APP_VERSION}`
en.softwareVersion = `v${APP_VERSION}`

export function useI18n() {
  const t = computed(() => (locale.value === 'zh' ? zh : en))
  function toggleLocale() {
    locale.value = locale.value === 'zh' ? 'en' : 'zh'
    localStorage.setItem('locale', locale.value)
  }
  return { locale, t, toggleLocale }
}

export function statusLabel(status: string | undefined, t: Record<string, string>) {
  if (status === 'online') return t.online
  if (status === 'degraded') return t.degraded
  if (status === 'offline') return t.offline
  if (status === 'maintenance') return t.maintenance || t.offline
  return t.unknown
}
