import { expect, test } from '@playwright/test'

test('admin token can load the source management page', async ({ page }) => {
  test.skip(!process.env.E2E_ADMIN_PASSWORD, 'Set E2E_ADMIN_PASSWORD to run the authenticated admin flow.')
  await page.goto('/admin')
  await page.getByLabel(/用户名|Username/).fill(process.env.E2E_ADMIN_USERNAME || 'admin')
  await page.getByLabel(/密码|Password/).fill(process.env.E2E_ADMIN_PASSWORD as string)
  await page.getByRole('button', { name: /登录|Sign in/ }).click()
  await expect(page.getByText(/管理后台|Admin/)).toBeVisible()
  await expect(page.getByRole('button', { name: /镜像源|Sources/ })).toBeVisible()
  await page.getByRole('button', { name: /Account|账户/ }).click()
  await expect(page.getByRole('button', { name: /退出|Sign out/ })).toBeVisible()
})

test('administrator can add, probe, inspect, and remove a source', async ({ page }) => {
  test.skip(!process.env.E2E_ADMIN_PASSWORD, 'Set E2E_ADMIN_PASSWORD to run the authenticated admin flow.')
  const name = `E2E Registry ${Date.now()}`
  page.on('dialog', dialog => dialog.accept())
  await page.goto('/admin')
  await page.getByLabel(/用户名|Username/).fill(process.env.E2E_ADMIN_USERNAME || 'admin')
  await page.getByLabel(/密码|Password/).fill(process.env.E2E_ADMIN_PASSWORD as string)
  await page.getByRole('button', { name: /登录|Sign in/ }).click()
  await page.getByRole('button', { name: /新增|添加|Add/ }).first().click()
  await page.getByLabel(/名称|Name/).fill(name)
  await page.getByLabel(/地址|URL/).fill('https://registry-1.docker.io')
  await page.getByLabel(/分类|Category/).selectOption('dockerhub')
  await page.getByRole('button', { name: /保存|Save/ }).click()
  const row = page.getByRole('row').filter({ hasText: name })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: 'Probe' }).click()
  await expect(page.getByText(/探测任务已加入队列|Probe task queued/)).toBeVisible()
  await page.getByRole('button', { name: /探测任务|Tasks/ }).click()
  await expect(page.getByText(/探测任务|Probe tasks/)).toBeVisible()
  await page.getByRole('button', { name: /镜像源|Sources/ }).click()
  await row.getByRole('button', { name: /删除|Delete/ }).click()
  await expect(row).toHaveCount(0)
})
